CREATE TABLE Filtros (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    GONHER NVARCHAR(50) NOT NULL,
    WALMI NVARCHAR(50) NOT NULL,
    FRAM NVARCHAR(50) NOT NULL,
    ENGINE NVARCHAR(50) NOT NULL,
    PUROLATOR NVARCHAR(50) NOT NULL,
    INTERFIL NVARCHAR(50) NOT NULL,
    [PREMIUM GUARD] NVARCHAR(50) NOT NULL,
    WIX NVARCHAR(50) NOT NULL,
    OEM NVARCHAR(50) NOT NULL,
    
);
GO